"""CartoonGAN - CycleGAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KO5kDbc-HDjUuEwroOFE-lf4Aiof9GaG

# 0. Import necessary Libraries
"""

import torch
import tensorflow as tf
from torch import nn
from torchvision import datasets
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt
import kagglehub
import os
import shutil
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
import datetime
import time
from sklearn.model_selection import train_test_split
import tensorflow_datasets as tfds
from tensorflow_examples.models.pix2pix import pix2pix    # we tried to import our pix2pix model we created, but had difficulty so we just grabbed the predefined version
from IPython.display import clear_output

AUTOTUNE = tf.data.AUTOTUNE

"""# 1. GPU"""

device = "cuda" if torch.cuda.is_available() else "cpu"
dtype = torch.float16 if device == "cuda" else torch.float32

"""# 2. Dataset

## Load Human Dataset
"""
# backend\gan_architecture\data\face2comics_v2.0.0_by_Sxela\face2comics_v2.0.0_by_Sxela\faces\0.jpg
# Get the directory where this script is located (models directory)
MODELS_DIR = os.path.dirname(os.path.abspath(__file__))
# Go up one level to gan_architecture directory
GAN_ARCH_DIR = os.path.dirname(MODELS_DIR)
# Go up one more level to backend directory
BACKEND_DIR = os.path.dirname(GAN_ARCH_DIR)
# Point to data folder (same level as models directory)
data_dir = os.path.join(GAN_ARCH_DIR, "data")
# Point to backend/models directory where models should be saved
SAVE_MODELS_DIR = os.path.join(BACKEND_DIR, "models")

# Create data directory if it doesn't exist
os.makedirs(data_dir, exist_ok=True)

# Check if dataset already exists, if not download it
expected_path = os.path.join(data_dir, "face2comics_v2.0.0_by_Sxela", "face2comics_v2.0.0_by_Sxela")
if not os.path.exists(expected_path):
    print("Dataset not found. Downloading from Kaggle...")
    # Download dataset - kagglehub downloads to a default location
    downloaded_path = kagglehub.dataset_download("defileroff/comic-faces-paired-synthetic-v2")
    print(f"Dataset downloaded to: {downloaded_path}")
    
    # Find the dataset folder in the downloaded location
    # kagglehub typically downloads to ~/.cache/kagglehub/datasets/...
    dataset_folder = None
    if os.path.exists(os.path.join(downloaded_path, "face2comics_v2.0.0_by_Sxela")):
        dataset_folder = os.path.join(downloaded_path, "face2comics_v2.0.0_by_Sxela")
    else:
        # Search for the dataset folder
        for root, dirs, files in os.walk(downloaded_path):
            if "face2comics_v2.0.0_by_Sxela" in dirs:
                dataset_folder = os.path.join(root, "face2comics_v2.0.0_by_Sxela")
                break
    
    if dataset_folder and dataset_folder != os.path.join(data_dir, "face2comics_v2.0.0_by_Sxela"):
        # Copy dataset to data folder
        target_folder = os.path.join(data_dir, "face2comics_v2.0.0_by_Sxela")
        print(f"Copying dataset to data folder: {target_folder}")
        if os.path.exists(target_folder):
            shutil.rmtree(target_folder)
        shutil.copytree(dataset_folder, target_folder)
        print("Dataset copied successfully!")
        path_to_dataset = data_dir
    else:
        # Use the downloaded path directly if copy failed
        path_to_dataset = downloaded_path
        print(f"Using dataset at download location: {downloaded_path}")
else:
    # Dataset exists in data folder
    path_to_dataset = data_dir
    print(f"Using existing dataset at: {path_to_dataset}")

#directory paths
path = os.path.join(path_to_dataset, "face2comics_v2.0.0_by_Sxela/face2comics_v2.0.0_by_Sxela")
photo_dir = os.path.join(path, "faces")
comic_dir = os.path.join(path, "comics")

# Split into train/test (80/20 split used in the tutorials)
all_photo_files = list((i for i in sorted(os.listdir(photo_dir))))
all_comic_files = list((i for i in sorted(os.listdir(comic_dir))))
train_photo_files, test_photo_files = train_test_split(
    all_photo_files, test_size=0.2, random_state=42
)
train_comic_files, test_comic_files = train_test_split(
    all_comic_files, test_size=0.2, random_state=42
)

# Create full paths
train_photo_paths = [os.path.join(photo_dir, f) for f in train_photo_files]
test_photo_paths = [os.path.join(photo_dir, f) for f in test_photo_files]
train_comic_paths = [os.path.join(comic_dir, f) for f in train_comic_files]
test_comic_paths = [os.path.join(comic_dir, f) for f in test_comic_files]

# Create TensorFlow datasets
def load_image(path):
    img = tf.io.read_file(path)
    img = tf.image.decode_jpeg(img, channels=3)
    return img
# Create datasets (matching the CycleGAN structure)
train_faces = tf.data.Dataset.from_tensor_slices(train_photo_paths).map(
    load_image, num_parallel_calls=tf.data.AUTOTUNE
)
test_faces = tf.data.Dataset.from_tensor_slices(test_photo_paths).map(
    load_image, num_parallel_calls=tf.data.AUTOTUNE
)
train_comics = tf.data.Dataset.from_tensor_slices(train_comic_paths).map(
    load_image, num_parallel_calls=tf.data.AUTOTUNE
)
test_comics = tf.data.Dataset.from_tensor_slices(test_comic_paths).map(
    load_image, num_parallel_calls=tf.data.AUTOTUNE
)

"""# 3. Preprocess Training Data

Similar to pix2pix notebook, we wanted to apply some random jittering and mirroring so model can get a good sense of variety of the same image. My guess is this reduces bias so the model does not work by purely memorizing
"""

BUFFER_SIZE = 1000
BATCH_SIZE = 1
IMG_WIDTH = 256
IMG_HEIGHT = 256

def random_crop(image):
  cropped_image = tf.image.random_crop(
      image, size=[IMG_HEIGHT, IMG_WIDTH, 3])

  return cropped_image

# normalizing the images to [-1, 1]
def normalize(image):
  image = tf.cast(image, tf.float32)
  image = (image / 127.5) - 1
  return image
def random_jitter(image):
  # resizing to 286 x 286 x 3
  image = tf.image.resize(image, [286, 286],
                          method=tf.image.ResizeMethod.NEAREST_NEIGHBOR)

  # randomly cropping to 256 x 256 x 3
  image = random_crop(image)

  # random mirroring
  image = tf.image.random_flip_left_right(image)

  return image

def preprocess_image_train(image):
  image = random_jitter(image)
  image = normalize(image)
  return image

def preprocess_image_test(image):
  image = normalize(image)
  return image

train_faces = train_faces.cache().map(
    preprocess_image_train, num_parallel_calls=AUTOTUNE).shuffle(
    BUFFER_SIZE).batch(BATCH_SIZE)

train_comics = train_comics.cache().map(
    preprocess_image_train, num_parallel_calls=AUTOTUNE).shuffle(
    BUFFER_SIZE).batch(BATCH_SIZE)

test_faces = test_faces.map(
    preprocess_image_test, num_parallel_calls=AUTOTUNE).cache().shuffle(
    BUFFER_SIZE).batch(BATCH_SIZE)

test_comics = test_comics.map(
    preprocess_image_test, num_parallel_calls=AUTOTUNE).cache().shuffle(
    BUFFER_SIZE).batch(BATCH_SIZE)

sample_face = next(iter(train_faces))
sample_comic = next(iter(train_comics))

"""# 4. Define Generators and Discriminators

We didn't want to focus this notebook on creating the same models, so we just pretty much grabbed the same generators and discriminators used in pix2pix. For more detail on each Neural Network, see our pix2pix notebook
"""
OUTPUT_CHANNELS = 3

generator_g = pix2pix.unet_generator(OUTPUT_CHANNELS, norm_type='instancenorm')
generator_f = pix2pix.unet_generator(OUTPUT_CHANNELS, norm_type='instancenorm')

discriminator_x = pix2pix.discriminator(norm_type='instancenorm', target=False)
discriminator_y = pix2pix.discriminator(norm_type='instancenorm', target=False)

to_comic = generator_g(sample_comic)
to_face = generator_f(sample_face)
plt.figure(figsize=(8, 8))
contrast = 8

"""Unlike the pix2pix, we don't want any influence from real and generated loss; thus, we define lambda as 1"""

LAMBDA = 1

loss_obj = tf.keras.losses.BinaryCrossentropy(from_logits=True)

def discriminator_loss(real, generated):
  real_loss = loss_obj(tf.ones_like(real), real)

  generated_loss = loss_obj(tf.zeros_like(generated), generated)

  total_disc_loss = real_loss + generated_loss

  return total_disc_loss * 0.5

def generator_loss(generated):
  return loss_obj(tf.ones_like(generated), generated)

def calc_cycle_loss(real_image, cycled_image):
  loss1 = tf.reduce_mean(tf.abs(real_image - cycled_image))

  return LAMBDA * loss1

def identity_loss(real_image, same_image):
  loss = tf.reduce_mean(tf.abs(real_image - same_image))
  return LAMBDA * 0.5 * loss

generator_g_optimizer = tf.keras.optimizers.Adam(2e-4, beta_1=0.5)
generator_f_optimizer = tf.keras.optimizers.Adam(2e-4, beta_1=0.5)

discriminator_x_optimizer = tf.keras.optimizers.Adam(2e-4, beta_1=0.5)
discriminator_y_optimizer = tf.keras.optimizers.Adam(2e-4, beta_1=0.5)

checkpoint_path = "./checkpoints/train"

ckpt = tf.train.Checkpoint(generator_g=generator_g,
                           generator_f=generator_f,
                           discriminator_x=discriminator_x,
                           discriminator_y=discriminator_y,
                           generator_g_optimizer=generator_g_optimizer,
                           generator_f_optimizer=generator_f_optimizer,
                           discriminator_x_optimizer=discriminator_x_optimizer,
                           discriminator_y_optimizer=discriminator_y_optimizer)

ckpt_manager = tf.train.CheckpointManager(ckpt, checkpoint_path, max_to_keep=5)

# if a checkpoint exists, restore the latest checkpoint.
if ckpt_manager.latest_checkpoint:
  ckpt.restore(ckpt_manager.latest_checkpoint)
  print ('Latest checkpoint restored!!')

EPOCHS = 10

def generate_images(model, test_input):
  prediction = model(test_input)

  plt.figure(figsize=(12, 12))

  display_list = [test_input[0], prediction[0]]
  title = ['Input Image', 'Predicted Image']

  for i in range(2):
    plt.subplot(1, 2, i+1)
    plt.title(title[i])
    # getting the pixel values between [0, 1] to plot it.
    plt.imshow(display_list[i] * 0.5 + 0.5)
    plt.axis('off')
  plt.show()

"""# 5. Trainning"""
@tf.function
def train_step(real_x, real_y):
  # persistent is set to True because the tape is used more than
  # once to calculate the gradients.
  with tf.GradientTape(persistent=True) as tape:
    # Generator G translates X -> Y
    # Generator F translates Y -> X.

    fake_y = generator_g(real_x, training=True)
    cycled_x = generator_f(fake_y, training=True)

    fake_x = generator_f(real_y, training=True)
    cycled_y = generator_g(fake_x, training=True)

    # same_x and same_y are used for identity loss.
    same_x = generator_f(real_x, training=True)
    same_y = generator_g(real_y, training=True)

    disc_real_x = discriminator_x(real_x, training=True)
    disc_real_y = discriminator_y(real_y, training=True)

    disc_fake_x = discriminator_x(fake_x, training=True)
    disc_fake_y = discriminator_y(fake_y, training=True)

    # calculate the loss
    gen_g_loss = generator_loss(disc_fake_y)
    gen_f_loss = generator_loss(disc_fake_x)

    total_cycle_loss = calc_cycle_loss(real_x, cycled_x) + calc_cycle_loss(real_y, cycled_y)

    # Total generator loss = adversarial loss + cycle loss
    total_gen_g_loss = gen_g_loss + total_cycle_loss + identity_loss(real_y, same_y)
    total_gen_f_loss = gen_f_loss + total_cycle_loss + identity_loss(real_x, same_x)

    disc_x_loss = discriminator_loss(disc_real_x, disc_fake_x)
    disc_y_loss = discriminator_loss(disc_real_y, disc_fake_y)

  # Calculate the gradients for generator and discriminator
  generator_g_gradients = tape.gradient(total_gen_g_loss,
                                        generator_g.trainable_variables)
  generator_f_gradients = tape.gradient(total_gen_f_loss,
                                        generator_f.trainable_variables)

  discriminator_x_gradients = tape.gradient(disc_x_loss,
                                            discriminator_x.trainable_variables)
  discriminator_y_gradients = tape.gradient(disc_y_loss,
                                            discriminator_y.trainable_variables)

  # Apply the gradients to the optimizer
  generator_g_optimizer.apply_gradients(zip(generator_g_gradients,
                                            generator_g.trainable_variables))

  generator_f_optimizer.apply_gradients(zip(generator_f_gradients,
                                            generator_f.trainable_variables))

  discriminator_x_optimizer.apply_gradients(zip(discriminator_x_gradients,
                                                discriminator_x.trainable_variables))

  discriminator_y_optimizer.apply_gradients(zip(discriminator_y_gradients,
                                                discriminator_y.trainable_variables))
print(f"EPOCHS: {EPOCHS}")
for epoch in range(EPOCHS):
  start = time.time()

  n = 0
  for image_x, image_y in tf.data.Dataset.zip((train_faces, train_comics)):
    train_step(image_x, image_y)
    if n % 10 == 0:
      print ('.', end='')
    n += 1

  clear_output(wait=True)
  # Using a consistent image (sample_horse) so that the progress of the model
  # is clearly visible.
  generate_images(generator_g, sample_face)

  if (epoch + 1) % 5 == 0:
    ckpt_save_path = ckpt_manager.save()
    print ('Saving checkpoint for epoch {} at {}'.format(epoch+1,
                                                         ckpt_save_path))

  print ('Time taken for epoch {} is {} sec\n'.format(epoch + 1,
                                                      time.time()-start))

# Run the trained model on the test dataset
for inp in test_faces.take(5):
  generate_images(generator_g, inp)

# Save model to backend/models directory
os.makedirs(SAVE_MODELS_DIR, exist_ok=True)
model_save_path = os.path.join(SAVE_MODELS_DIR, 'cycle_gan_generator_g_model.keras')
generator_g.save(model_save_path)
print(f"Model saved to: {model_save_path}")