# -*- coding: utf-8 -*-
"""CartoonGAN - Pix2Pix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MxThv4SazSCjcm8Zc8WkA6PDHhBPJLCm

# 0. Import necessary Libraries
"""

import torch
import tensorflow as tf
from torch import nn
from torchvision import datasets
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt
import kagglehub
import os
import shutil
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
import datetime
import time

"""# 1. GPU"""

device = "cuda" if torch.cuda.is_available() else "cpu"
dtype = torch.float16 if device == "cuda" else torch.float32

"""# 2. Dataset

## Load Human Dataset
"""

# Get the directory where this script is located (models directory)
MODELS_DIR = os.path.dirname(os.path.abspath(__file__))
# Go up one level to gan_architecture directory
GAN_ARCH_DIR = os.path.dirname(MODELS_DIR)
# Go up one more level to backend directory
BACKEND_DIR = os.path.dirname(GAN_ARCH_DIR)
# Point to data folder (same level as models directory)
data_dir = os.path.join(GAN_ARCH_DIR, "data")
# Point to backend/models directory where models should be saved
SAVE_MODELS_DIR = os.path.join(BACKEND_DIR, "models")
# Create data directory if it doesn't exist
os.makedirs(data_dir, exist_ok=True)

# Check if dataset already exists, if not download it
expected_path = os.path.join(data_dir, "face2comics_v2.0.0_by_Sxela", "face2comics_v2.0.0_by_Sxela")
if not os.path.exists(expected_path):
    print("Dataset not found. Downloading from Kaggle...")
    # Download dataset - kagglehub downloads to a default location
    downloaded_path = kagglehub.dataset_download("defileroff/comic-faces-paired-synthetic-v2")
    print(f"Dataset downloaded to: {downloaded_path}")
    
    # Find the dataset folder in the downloaded location
    dataset_folder = None
    if os.path.exists(os.path.join(downloaded_path, "face2comics_v2.0.0_by_Sxela")):
        dataset_folder = os.path.join(downloaded_path, "face2comics_v2.0.0_by_Sxela")
    else:
        # Search for the dataset folder
        for root, dirs, files in os.walk(downloaded_path):
            if "face2comics_v2.0.0_by_Sxela" in dirs:
                dataset_folder = os.path.join(root, "face2comics_v2.0.0_by_Sxela")
                break
    
    if dataset_folder and dataset_folder != os.path.join(data_dir, "face2comics_v2.0.0_by_Sxela"):
        # Copy dataset to data folder
        target_folder = os.path.join(data_dir, "face2comics_v2.0.0_by_Sxela")
        print(f"Copying dataset to data folder: {target_folder}")
        if os.path.exists(target_folder):
            shutil.rmtree(target_folder)
        shutil.copytree(dataset_folder, target_folder)
        print("Dataset copied successfully!")
        path_to_dataset = data_dir
    else:
        # Use the downloaded path directly if copy failed
        path_to_dataset = downloaded_path
        print(f"Using dataset at download location: {downloaded_path}")
else:
    # Dataset exists in data folder
    path_to_dataset = data_dir
    print(f"Using existing dataset at: {path_to_dataset}")

#directory paths
path = os.path.join(path_to_dataset, "face2comics_v2.0.0_by_Sxela/face2comics_v2.0.0_by_Sxela")
photo_dir = os.path.join(path, "faces")
comic_dir = os.path.join(path, "comics")

"""## Visualize some of them"""

all_photo_files = list((i for i in sorted(os.listdir(photo_dir))))
all_comic_files = list((i for i in sorted(os.listdir(comic_dir))))

photo_files = all_photo_files[:5]
comic_files = all_comic_files[:5]

# Create subplot grid
fig, axes = plt.subplots(1, len(photo_files) * 2, figsize=(20, 4))

# Handle case where there's only one pair
if len(photo_files) == 1:
    axes = [axes]

for i, fname in enumerate(photo_files[:5]):
    photo_path = os.path.join(photo_dir, fname)
    comic_path = os.path.join(comic_dir, fname)

    photo = Image.open(photo_path).convert("RGB")
    comic = Image.open(comic_path).convert("RGB")

    axes[2*i].imshow(photo)
    axes[2*i].set_title(f"Original {i+1}")
    axes[2*i].axis("off")

    axes[2*i+1].imshow(comic)
    axes[2*i+1].set_title(f"Comic {i+1}")
    axes[2*i+1].axis("off")

plt.tight_layout()
plt.show()

"""## Perform Datachecks and representation."""

photo_path = os.path.join(photo_dir, photo_files[0])
photo = Image.open(photo_path).convert("RGB")
# convert to numpy array
photo = np.array(photo)

# verify the size
print(f'photo size: {photo.size}')
print(f'photo type: {type(photo)}')
print(f'photo shape: {photo.shape}')

"""# 3. Pix2Pix Model"""

def load(face_file_path, comic_file_path):
  # Read and decode a face_file to a uint8 tensor
  image = tf.io.read_file(face_file_path)
  image = tf.io.decode_jpeg(image)

  # Read and decode a comic_file to a uint8 tensor
  label = tf.io.read_file(comic_file_path)
  label = tf.io.decode_jpeg(label)


  # Convert both images to float32 tensors
  input_image = tf.cast(image, tf.float32)
  output_image = tf.cast(label, tf.float32)

  return input_image, output_image

print(os.path.join(photo_dir, photo_files[0]))

print(os.path.join(path_to_dataset, comic_files[0]))

"""## Plot some of input and output image pairs"""

# plot a sample of the input and output images
photo_path = os.path.join(photo_dir, photo_files[0])
comic_path = os.path.join(comic_dir, comic_files[0])
input, output = load(photo_path, comic_path)

# Display the images (optional, for verification)
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(input.numpy().astype('uint8'))
plt.title("Input Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(output.numpy().astype('uint8'))
plt.title("Output Image")
plt.axis("off")

plt.show()

"""This was recommended in the tutorials, but we need to apply random Jittering and mirroring to preprocess the training data"""

# Total number of images
BUFFER_SIZE = len(photo_files)
BATCH_SIZE = 1
IMG_WIDTH = 1024
IMG_HEIGHT = 1024

def resize(input_image, output_image, height, width):
  input_image = tf.image.resize(input_image, [height, width],
                                method=tf.image.ResizeMethod.NEAREST_NEIGHBOR)
  output_image = tf.image.resize(output_image, [height, width],
                               method=tf.image.ResizeMethod.NEAREST_NEIGHBOR)

  return input_image, output_image

def random_crop(input_image, output_image):
  stacked_image = tf.stack([input_image, output_image], axis=0)
  cropped_image = tf.image.random_crop(
      stacked_image, size=[2, IMG_HEIGHT, IMG_WIDTH, 3])

  return cropped_image[0], cropped_image[1]

# Normalizing the images to [-1, 1]
def normalize(input_image, output_image):
  input_image = (input_image / 127.5) - 1
  output_image = (output_image / 127.5) - 1

  return input_image, output_image

@tf.function()
def random_jitter(input_image, output_image):
  # Resizing to 1054x1054
  input_image, output_image = resize(input_image, output_image, 1054, 1054)

  # Random cropping back to 256x256
  input_image, output_image = random_crop(input_image, output_image)

  if tf.random.uniform(()) > 0.5:
    # Random mirroring
    input_image = tf.image.flip_left_right(input_image)
    output_image = tf.image.flip_left_right(output_image)

  return input_image, output_image

"""# Inspect some of the preprocessed image(s)"""

plt.figure(figsize=(6, 6))
for i in range(4):
  rj_inp, rj_output = random_jitter(input, output)
  plt.subplot(2, 2, i + 1)
  plt.imshow(rj_inp / 255.0)
  plt.axis('off')
plt.show()

"""Preprocessing Works, Now define helper funtions for loading train and test"""

def load_image_train(input_file, output_file):
  def _load_image_train_py(input_file, output_file):
    input_path = os.path.join(photo_dir, input_file.numpy().decode('utf-8'))
    output_path = os.path.join(comic_dir, output_file.numpy().decode('utf-8'))
    input_image, output_image = load(input_path, output_path)
    input_image, output_image = random_jitter(input_image, output_image)
    input_image, output_image = normalize(input_image, output_image)
    return input_image, output_image

  input_image, output_image = tf.py_function(_load_image_train_py, [input_file, output_file], [tf.float32, tf.float32])
  input_image.set_shape([None, None, 3])
  output_image.set_shape([None, None, 3])
  return input_image, output_image

def load_image_test(input_file, output_file):
  def _load_image_test_py(input_file, output_file):
    input_path = os.path.join(photo_dir, input_file.numpy().decode('utf-8'))
    output_path = os.path.join(comic_dir, output_file.numpy().decode('utf-8'))
    input_image, output_image = load(input_path, output_path)
    input_image, output_image = resize(input_image, output_image,
                                     IMG_HEIGHT, IMG_WIDTH) #resize instead of random jitter
    input_image, output_image = normalize(input_image, output_image)
    return input_image, output_image

  input_image, output_image = tf.py_function(_load_image_test_py, [input_file, output_file], [tf.float32, tf.float32])
  input_image.set_shape([IMG_HEIGHT, IMG_WIDTH, 3])
  output_image.set_shape([IMG_HEIGHT, IMG_WIDTH, 3])
  return input_image, output_image

"""## Build an input pipeline with tf.data"""

#Build an input pipeline with tf.data, train_test split of 6000, 4000
train_dataset = tf.data.Dataset.from_tensor_slices((all_photo_files[:6000], all_comic_files[:6000]))
train_dataset = train_dataset.map(load_image_train,
                                  num_parallel_calls=tf.data.AUTOTUNE)
train_dataset = train_dataset.shuffle(BUFFER_SIZE)
# Use the defined BATCH_SIZE instead of loading all examples at once to avoid OOM
train_dataset = train_dataset.batch(BATCH_SIZE)
train_dataset = train_dataset.prefetch(tf.data.AUTOTUNE)

#create a test_dataset
test_dataset = tf.data.Dataset.from_tensor_slices((all_photo_files[6000:], all_comic_files[6000:]))
test_dataset = test_dataset.map(load_image_test)
test_dataset = test_dataset.batch(BATCH_SIZE)
test_dataset = test_dataset.prefetch(tf.data.AUTOTUNE)

"""## Build the generator"""

OUTPUT_CHANNELS = 3

def downsample(filters, size, apply_batchnorm=True):
  initializer = tf.random_normal_initializer(0., 0.02)

  result = tf.keras.Sequential()
  result.add(
      tf.keras.layers.Conv2D(filters, size, strides=2, padding='same',
                             kernel_initializer=initializer, use_bias=False))

  if apply_batchnorm:
    result.add(tf.keras.layers.BatchNormalization())

  result.add(tf.keras.layers.LeakyReLU())

  return result

down_model = downsample(3, 4)
down_result = down_model(tf.expand_dims(input, 0))
print (down_result.shape)

def upsample(filters, size, apply_dropout=False):
  initializer = tf.random_normal_initializer(0., 0.02)

  result = tf.keras.Sequential()
  result.add(
    tf.keras.layers.Conv2DTranspose(filters, size, strides=2,
                                    padding='same',
                                    kernel_initializer=initializer,
                                    use_bias=False))
  result.add(tf.keras.layers.BatchNormalization())

  if apply_dropout:
      result.add(tf.keras.layers.Dropout(0.5))

  result.add(tf.keras.layers.ReLU())

  return result

upmodel = upsample(3, 4)
up_result = upmodel(down_result)
print (up_result.shape)

"""## Define the Generator with the Upsample and downsample"""

def Generator():
  inputs = tf.keras.layers.Input(shape=[1024, 1024, 3])

  down_stack = [
    downsample(64, 4, apply_batchnorm=False),  # (batch_size, 128, 128, 64)
    downsample(128, 4),  # (batch_size, 64, 64, 128)
    downsample(256, 4),  # (batch_size, 32, 32, 256)
    downsample(512, 4),  # (batch_size, 16, 16, 512)
    downsample(512, 4),  # (batch_size, 8, 8, 512)
    downsample(512, 4),  # (batch_size, 4, 4, 512)
    downsample(512, 4),  # (batch_size, 2, 2, 512)
    downsample(512, 4),  # (batch_size, 1, 1, 512)
  ]

  up_stack = [
    upsample(512, 4, apply_dropout=True),  # (batch_size, 2, 2, 1024)
    upsample(512, 4, apply_dropout=True),  # (batch_size, 4, 4, 1024)
    upsample(512, 4, apply_dropout=True),  # (batch_size, 8, 8, 1024)
    upsample(512, 4),  # (batch_size, 16, 16, 1024)
    upsample(256, 4),  # (batch_size, 32, 32, 512)
    upsample(128, 4),  # (batch_size, 64, 64, 256)
    upsample(64, 4),  # (batch_size, 128, 128, 128)
  ]

  initializer = tf.random_normal_initializer(0., 0.02)
  last = tf.keras.layers.Conv2DTranspose(OUTPUT_CHANNELS, 4,
                                         strides=2,
                                         padding='same',
                                         kernel_initializer=initializer,
                                         activation='tanh')  # (batch_size, 256, 256, 3)

  x = inputs

  # Downsampling through the model
  skips = []
  for down in down_stack:
    x = down(x)
    skips.append(x)

  skips = reversed(skips[:-1])

  # Upsampling and establishing the skip connections
  for up, skip in zip(up_stack, skips):
    x = up(x)
    x = tf.keras.layers.Concatenate()([x, skip])

  x = last(x)

  return tf.keras.Model(inputs=inputs, outputs=x)

generator = Generator()

# Test the Generator
gen_output = generator(input[tf.newaxis, ...], training=False)
plt.imshow(gen_output[0, ...])

"""## Define the Generator loss"""

LAMBDA = 100    # the paper mentions to use 100 for lambda; showcases that accuracy is a big factor in loss?

loss_object = tf.keras.losses.BinaryCrossentropy(from_logits=True)

def generator_loss(disc_generated_output, gen_output, target):
  gan_loss = loss_object(tf.ones_like(disc_generated_output), disc_generated_output)

  # Mean absolute error
  l1_loss = tf.reduce_mean(tf.abs(target - gen_output))

  total_gen_loss = gan_loss + (LAMBDA * l1_loss)

  return total_gen_loss, gan_loss, l1_loss

"""## Discriminator"""

def Discriminator():
  initializer = tf.random_normal_initializer(0., 0.02)

  inp = tf.keras.layers.Input(shape=[1024, 1024, 3], name='input_image')
  tar = tf.keras.layers.Input(shape=[1024, 1024, 3], name='target_image')

  x = tf.keras.layers.concatenate([inp, tar])  # (batch_size, 1024, 1024, channels*2)

  down1 = downsample(64, 4, False)(x)  # (batch_size, 128, 128, 64)
  down2 = downsample(128, 4)(down1)  # (batch_size, 64, 64, 128)
  down3 = downsample(256, 4)(down2)  # (batch_size, 32, 32, 256)

  zero_pad1 = tf.keras.layers.ZeroPadding2D()(down3)  # (batch_size, 34, 34, 256)
  conv = tf.keras.layers.Conv2D(512, 4, strides=1,
                                kernel_initializer=initializer,
                                use_bias=False)(zero_pad1)  # (batch_size, 31, 31, 512)

  batchnorm1 = tf.keras.layers.BatchNormalization()(conv)

  leaky_relu = tf.keras.layers.LeakyReLU()(batchnorm1)

  zero_pad2 = tf.keras.layers.ZeroPadding2D()(leaky_relu)  # (batch_size, 33, 33, 512)

  last = tf.keras.layers.Conv2D(1, 4, strides=1,
                                kernel_initializer=initializer)(zero_pad2)  # (batch_size, 30, 30, 1)

  return tf.keras.Model(inputs=[inp, tar], outputs=last)

discriminator = Discriminator()

# test the discriminator
disc_out = discriminator([input[tf.newaxis, ...], gen_output], training=False)
plt.imshow(disc_out[0, ..., -1], vmin=-20, vmax=20, cmap='RdBu_r')
plt.colorbar()

"""## Descriminator loss"""

def discriminator_loss(disc_real_output, disc_generated_output):
  real_loss = loss_object(tf.ones_like(disc_real_output), disc_real_output)

  generated_loss = loss_object(tf.zeros_like(disc_generated_output), disc_generated_output)

  total_disc_loss = real_loss + generated_loss

  return total_disc_loss

# Optimizers and checkpoints

generator_optimizer = tf.keras.optimizers.Adam(2e-4, beta_1=0.5)
discriminator_optimizer = tf.keras.optimizers.Adam(2e-4, beta_1=0.5)

checkpoint_dir = './training_checkpoints'
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt")
checkpoint = tf.train.Checkpoint(generator_optimizer=generator_optimizer,
                                 discriminator_optimizer=discriminator_optimizer,
                                 generator=generator,
                                 discriminator=discriminator)

"""## Generated images"""

def generate_images(model, test_input, tar):
  prediction = model(test_input, training=True)
  plt.figure(figsize=(15, 15))

  display_list = [test_input[0], tar[0], prediction[0]]
  title = ['Input Image', 'Ground Truth', 'Predicted Image']

  for i in range(3):
    plt.subplot(1, 3, i+1)
    plt.title(title[i])
    # Getting the pixel values in the [0, 1] range to plot.
    plt.imshow(display_list[i] * 0.5 + 0.5)
    plt.axis('off')
  plt.show()

# Test the function
for example_input, example_target in train_dataset.take(1):
  generate_images(generator, example_input, example_target)

"""## Training"""

log_dir="logs/"

summary_writer = tf.summary.create_file_writer(
  log_dir + "fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))

@tf.function
def train_step(input_image, target, step):
  with tf.GradientTape() as gen_tape, tf.GradientTape() as disc_tape:
    gen_output = generator(input_image, training=True)

    # Call 1: Real pair (input + target)
    disc_real_output = discriminator([input_image, target], training=True)

    # Call 2: Fake pair (input + generated)
    disc_generated_output = discriminator([input_image, gen_output], training=True)

    gen_total_loss, gen_gan_loss, gen_l1_loss = generator_loss(disc_generated_output, gen_output, target)
    disc_loss = discriminator_loss(disc_real_output, disc_generated_output)

  generator_gradients = gen_tape.gradient(gen_total_loss,
                                          generator.trainable_variables)
  discriminator_gradients = disc_tape.gradient(disc_loss,
                                               discriminator.trainable_variables)

  generator_optimizer.apply_gradients(zip(generator_gradients,
                                          generator.trainable_variables))
  discriminator_optimizer.apply_gradients(zip(discriminator_gradients,
                                              discriminator.trainable_variables))

  with summary_writer.as_default():
    tf.summary.scalar('gen_total_loss', gen_total_loss, step=step//1000)
    tf.summary.scalar('gen_gan_loss', gen_gan_loss, step=step//1000)
    tf.summary.scalar('gen_l1_loss', gen_l1_loss, step=step//1000)
    tf.summary.scalar('disc_loss', disc_loss, step=step//1000)

from IPython import display

def fit(train_ds, test_ds, steps):
  example_input, example_target = next(iter(test_ds.take(1)))
  start = time.time()

  for step, (input_image, target) in train_ds.repeat().take(steps).enumerate():
    if (step) % 1000 == 0:
      display.clear_output(wait=True)

      if step != 0:
        print(f'Time taken for 1000 steps: {time.time()-start:.2f} sec\n')

      start = time.time()

      generate_images(generator, example_input, example_target)
      print(f"Step: {step//1000}k")

    train_step(input_image, target, step)

    # Training step
    if (step+1) % 10 == 0:
      print('.', end='', flush=True)


    # Save (checkpoint) the model every 5k steps
    if (step + 1) % 5000 == 0:
      checkpoint.save(file_prefix=checkpoint_prefix)

fit(train_dataset, test_dataset, steps=200000)

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir {log_dir}

"""##"""



#test the current model on some test sets
for inp, tar in test_dataset.take(5):
  generate_images(generator, inp, tar)

"""## Saving the Generator Model

To use the trained generator model in an API, we can save it in the SavedModel format, which is a standard way to serialize TensorFlow models.
"""

# Save the generator model to backend/models directory
os.makedirs(SAVE_MODELS_DIR, exist_ok=True)
model_save_path = os.path.join(SAVE_MODELS_DIR, 'pix2pix_generator_model.keras')
generator.save(model_save_path)
print(f"Model saved to: {model_save_path}")